import numpy as np

# ---------------------------------------------------------------------------
#    Force models
# ---------------------------------------------------------------------------
def F_ice(F_trac_max, P_ice_max, v):
    """Force generated by the Internal Combustion Engine.
    Traction-limited at low speed, power-limited at high speed."""
    return np.minimum(F_trac_max, P_ice_max / np.maximum(v, 1.0))

def F_MGUK(P_mguk_max, u_row, v_col):
    """Force Generated by the Motor Generator Unit -- Kinetic"""
    return u_row * P_mguk_max / v_col

def F_drag(rho_air, CdA, v, drag_mult):
    """Opposing force generated by drag"""
    return 0.5 * rho_air * CdA * drag_mult * v**2

def F_rolling(Crr, m, g):
    """ Opposing generated by rolling friction. Constant."""
    return Crr * m * g

# ---------------------------------------------------------------------------
#    Braking-zone flags, regen energy potential R(d_t) & Drag Multiplier dynamics
# ---------------------------------------------------------------------------
def braking_zones_and_regen(m, P_mguk_max, vmax, ds):
    n_seg = len(vmax) - 1
    BZ = np.zeros(n_seg, dtype=bool)
    R = np.zeros(n_seg)
    for t in range(n_seg):
        if vmax[t + 1] < vmax[t] - 2.0:      # must shed speed -> braking zone
            BZ[t] = True
            v_avg = 0.5 * (vmax[t] + vmax[t + 1])

            # ---- BRAKE-BATTERY HARVEST DYNAMICS ----
            t_brake = ds / max(v_avg, 1.0)
            energy_available = 0.5 * m * (vmax[t]**2 - vmax[t + 1]**2)
            R[t] = min(P_mguk_max * t_brake, energy_available)
            # ---- ----

    return BZ, R

def drag_multiplier(kappa, kappa_thresh=1.0 / 300.0):
    """Straights (low curvature) run a lower-drag / DRS-like aero setting."""
    return np.where(np.abs(kappa) < kappa_thresh, 0.80, 1.00)